import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import AOSProvider from "./AOSProvider";
import HeaderSection from "./components/header_section";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} antialiased`}>
         < HeaderSection />
    

        <AOSProvider>

          {children}
        </AOSProvider>
      </body>
    </html>
  );
}
